### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark-repl#1]
Please document, so that even I can understand it, how I can start this up so that it listens on `localhost:5001` (then I can forward requests from an nginx frontend).

**Comment by WilliamDue** [comment]
I have now described (Inside README.md) and added a way to specify the port for which the server listens on in the main branch. Currently it always uses the IP: 0.0.0.0 to listen on since since I have had some trouble specifying other IPs in the Dockerfile using waitress. Is this good enough or would I have to look some more into it?
